modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Lunar/issues"
license="MIT"

[[mods]]
modId="lunar"
version="${file.jarVersion}"
displayName="Lunar"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lunar"
logoFile="icon.png"
authors="Mrbysco"
description='''
Adding Lunar events to the game
'''
[[dependencies.lunar]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="lunar.mixins.json"